// export { default as AppWidget } from './AppWidget';
export { default as AppSlider } from './AppSlider';
export { default as AppWelcome } from './AppWelcome';
export { default as AppDialog } from './AppDialog';
export { default as AppWelcome1 } from './AppWelcome1';
export { default as AppFeatured } from './AppFeatured';
export { default as AppFeatured1 } from './AppFeatured1';
export { default as AppWidgetSummary } from './AppWidgetSummary';
export { default as TableList } from './TableList';
export { default as Canva } from './Canva';
// export { default as Canva1 } from './Canva1';
export { default as PlanCards } from './PlanCards';
export { default as JigsawGame } from './JigsawGame';
export { default as EventDialog } from './EventDialog';
export { default as EventCard } from './EventCard';
export { default as QuizRadio } from "./QuizRadio";
// export { default as CardWithCanvas } from "./CardWithCanvas";